hj - cicd:22트

diff --git a/.github/workflows/ec2_deploy.yml b/.github/workflows/ec2_deploy.yml
--- a/.github/workflows/ec2_deploy.yml
+++ b/.github/workflows/ec2_deploy.yml
@@ -72,6 +72,7 @@ jobs:
       - name: Verify downloaded file existence
         run: |
           echo "Verifying downloaded file..."
+          find ${{ github.workspace }} -name "hikingclub-0.0.1-SNAPSHOT.jar" || echo "File not found"
           ls -l ${{ github.workspace }}/hikingclub/build/libs/
 
       - name: Copy file via SSH
