cicd 5트

diff --git a/.github/workflows/ec2_deploy.yml b/.github/workflows/ec2_deploy.yml
--- a/.github/workflows/ec2_deploy.yml
+++ b/.github/workflows/ec2_deploy.yml
@@ -11,21 +11,13 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
-      - name: Install Amazon Corretto JDK 17
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y wget
-          wget -qO- https://apt.corretto.aws/corretto.key | sudo apt-key add -
-          sudo add-apt-repository 'deb https://apt.corretto.aws stable main'
-          sudo apt-get update
-          sudo apt-get install -y java-17-amazon-corretto-jdk
-
-      - name: Set environment variables for Java
-        run: |
-          echo "JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto" >> $GITHUB_ENV
-          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'corretto'
 
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
@@ -40,7 +32,7 @@ jobs:
         working-directory: hikingclub
 
       - name: Archive JAR file
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v3
         with:
           name: hikingclub-jar
           path: hikingclub/build/libs/hikingclub-0.0.1-SNAPSHOT.jar
@@ -51,14 +43,14 @@ jobs:
 
     steps:
       - name: Download JAR artifact
-        uses: actions/download-artifact@v2
+        uses: actions/download-artifact@v3
         with:
           name: hikingclub-jar
 
       - name: Verify downloaded file existence
         run: |
           echo "Verifying downloaded file..."
-          find ${{ github.workspace }} -name "hikingclub-0.0.1-SNAPSHOT.jar" || echo "File not found"
+          find . -name "hikingclub-0.0.1-SNAPSHOT.jar" || echo "File not found"
 
       - name: Copy file via SSH
         uses: appleboy/scp-action@v0.1.7
@@ -66,7 +58,7 @@ jobs:
           host: ${{ secrets.AWS_HOST }}
           username: ${{ secrets.AWS_USERNAME }}
           key: ${{ secrets.AWS_KEY }}
-          source: "${{ github.workspace }}/hikingclub/build/libs/hikingclub-0.0.1-SNAPSHOT.jar"
+          source: "hikingclub-0.0.1-SNAPSHOT.jar"
           target: "~/hikingclub-0.0.1-SNAPSHOT.jar"
           debug: true
           overwrite: true
